name: atrak
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1 

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  build_resolvers: ^1.3.10
  analyzer: ^0.39.0
  path_provider: ^0.4.1
  dio: ^1.0.6
  vibrate: ^0.0.4
  flutter_calendar: ^0.0.8
  location: ^1.4.1
  simple_permissions: ^0.1.9
  geocoder: ^0.1.2
  sqflite: ^1.3.0
  #jaguar_orm: ^2.2.0
  #jaguar_query_sqflite: ^2.2.0
  fluttertoast: ^2.1.2
  flutter_bloc: ^0.4.7
  fimber: ^0.1.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  mockito: ^3.0.0
  test: ^1.3.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  intl_translation: ^0.17.10
  build_runner: ^1.10.0
  jaguar_orm_gen: ^2.2.22


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: WorkSanks
      fonts:
        - asset:  assets/fonts/WorkSans-Thin.ttf
          weight: 100
        - asset:  assets/fonts/WorkSans-ExtraLight.ttf
          weight: 200
        - asset:  assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset:  assets/fonts/WorkSans-Regular.ttf
          weight:  400
        - asset:  assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset:  assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset:  assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset:  assets/fonts/WorkSans-ExtraBold.ttf
          weight: 800
        - asset:  assets/fonts/WorkSans-Black.ttf
          weight: 900


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
